---
# tasks file for user_create

- name: add user 
  user:
    name: "{{item.user | default(omit)}}"
    password: "{{item.passwd | default(omit)}}"
    expires: -1
    group: "{{item.group | default(omit)}}"
    shell: "{{item.shell | default(omit)}}"
    home: "{{item.home | default (omit)}}"
  loop: "{{new_users}}"
  tags: 
    - add_user
