---
# tasks file for prerequisitos

- name: disable selinux
  selinux:
    state: disabled
  tags:
    - selinux

- name: dns
  lineinfile:
    path: /etc/hosts
    line: "{{ansible_default_ipv4.address}} {{ansible_hostname}}.lab.data.com.py"
  tags: 
    - dns

- name: firewall
  firewalld:
    zone: public
    service: http
    permanent: yes
    state: enabled
  tags:
    - firewall

- name: directory 
  file:
    path: /root/custom_dir
    state: directory
  tags:
    - directory
    
