---
# Install customs facts
- name: directory for customs facts
  file:
    state: directory
    recurse: yes
    path: /etc/ansible/facts.d

- name: pass customs facts
  template:
    src: ./templates/custom.fact.j2
    dest: /etc/ansible/facts.d/custom.fact
  tags:
    - facts

- name: ah 
  debug:
    msg: "{{ansible_local.custom.service.name_service}}"
  tags:
    - msg
